export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  spaceApiBaseUrl: process.env.SPACE_API_BASE_URL ?? "",
  spaceApiKey: process.env.SPACE_API_KEY ?? "",
  spaceDefaultRadius: parseInt(process.env.SPACE_DEFAULT_RADIUS ?? "1500"),
  spaceMaxRadius: parseInt(process.env.SPACE_MAX_RADIUS ?? "5000"),
  googlePlacesApiKey: process.env.GOOGLE_PLACES_API_KEY ?? "",
};
